---
language: python
python: "2.7"
php:
  - "5.6"

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  # Install ansible
  - pip install ansible

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - cd tests
  - ansible-playbook ./test.yml -i inventory --syntax-check
  - ansible-playbook -i inventory ./test.yml --sudo -vvvv
  - behat | cat

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/