---
# file: roles/fubarhouse.behat/tasks/behat.yml

- name: "Behat | Check"
  become: yes
  become_user: "root"
  file:
    path: "{{ behat_dir }}"
    state: directory
    owner: "{{ fubarhouse_user }}"
    mode: 0755

- name: "Behat | Installing"
  composer:
    command: "require"
    arguments: "{{ behat_package }}:{{ behat_version }}"
    working_dir: "{{ behat_dir }}"

- name: "Behat | Installing Extensions"
  composer:
    command: "require"
    arguments: "{{ item.package }}:{{ item.version }}"
    working_dir: "{{ behat_dir }}"
  with_items: "{{ behat_extensions }}"

- name: "Behat | Symlinking"
  file:
    src: "{{ behat_exec }}"
    dest: "{{ behat_sym }}"
    owner: "{{ fubarhouse_user }}"
    state: "link"