---
# file: roles/fubarhouse.behat/tasks/behat.yml

- name: Behat | Check
  stat: path="{{ behat_location }}"
  register: behat_result

- name: Behat | Git
  git: repo=https://github.com/Behat/Behat
       dest={{ behat_dir }}
       clone=yes
       update=yes
       version=master

- name: Behat | Get installer
  shell: "cd {{ behat_dir }} && curl -s http://getcomposer.org/installer | php"
  when: not behat_result.stat.exists

- name: Behat | Install
  composer:  working-dir={{ behat_dir }}
  when: not behat_result.stat.exists

- name: "Behat | Configure"
  raw: echo 'alias behat="./bin/behat"' >> ~/.bashrc
  when: not behat_result.stat.exists
