---
# file: roles/fubarhouse.behat/tasks/behat.yml

- name: "Drupal Extension | Check"
  become: yes
  become_user: "root"
  file:
    path: "{{ fubarhouse_behat.extension_dir }}"
    state: directory
    owner: "{{ fubarhouse_user }}"
    mode: 0755

- name: "Drupal Extension | Check"
  template:
    src: "templates/drupal-extension.json"
    dest: "{{ fubarhouse_behat.extension_dir }}/composer.json"
    owner: "{{ fubarhouse_user }}"
    mode: 0755

- name: "Drupal Extension | Installing"
  composer:
    command: "install"
    working_dir: "{{ fubarhouse_behat.extension_dir }}"

- name: "Drupal Extension | Symlinking"
  file:
    src: "{{ fubarhouse_behat.extension_exec }}"
    dest: "{{ fubarhouse_behat.extension_sym }}"
    owner: "{{ fubarhouse_user }}"
    state: "link"